// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <dplyr.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4eDNAoccupancy_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lm_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4logistic_stan_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4logistic_target_stan_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4occupancy_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4occupancyBernoulli_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4occupancy_bernoulli_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4occupancy_mu_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4occupancy_mu_binomial_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4eDNAoccupancy_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4eDNAoccupancy_mod, 0},
    {"_rcpp_module_boot_stan_fit4lm_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lm_mod, 0},
    {"_rcpp_module_boot_stan_fit4logistic_stan_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4logistic_stan_mod, 0},
    {"_rcpp_module_boot_stan_fit4logistic_target_stan_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4logistic_target_stan_mod, 0},
    {"_rcpp_module_boot_stan_fit4occupancy_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4occupancy_mod, 0},
    {"_rcpp_module_boot_stan_fit4occupancyBernoulli_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4occupancyBernoulli_mod, 0},
    {"_rcpp_module_boot_stan_fit4occupancy_bernoulli_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4occupancy_bernoulli_mod, 0},
    {"_rcpp_module_boot_stan_fit4occupancy_mu_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4occupancy_mu_mod, 0},
    {"_rcpp_module_boot_stan_fit4occupancy_mu_binomial_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4occupancy_mu_binomial_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rstanOcc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
